import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface MemoExportData {
  title: string;
  content: string;
  author: string;
  createdAt: string;
  borrowerName?: string;
  loanName?: string;
  generatedByAi?: boolean;
}

interface CovenantTestExportData {
  loanName: string;
  borrowerName: string;
  periodEndDate: string;
  testedAt: string;
  results: {
    covenantName: string;
    type: string;
    calculatedValue: number;
    threshold: number;
    operator: string;
    headroomPercentage: number;
    status: string;
  }[];
}

/**
 * Export a memo to PDF
 */
export function exportMemoToPDF(data: MemoExportData): jsPDF {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(10);
  doc.setTextColor(128);
  doc.text("TERMLY - Credit Memo", 14, 15);

  // Title
  doc.setFontSize(20);
  doc.setTextColor(0);
  doc.text(data.title, 14, 30);

  // Meta information
  doc.setFontSize(10);
  doc.setTextColor(100);
  let yPos = 40;

  if (data.borrowerName) {
    doc.text(`Borrower: ${data.borrowerName}`, 14, yPos);
    yPos += 6;
  }
  if (data.loanName) {
    doc.text(`Loan: ${data.loanName}`, 14, yPos);
    yPos += 6;
  }
  doc.text(`Author: ${data.author}`, 14, yPos);
  yPos += 6;
  doc.text(`Created: ${data.createdAt}`, 14, yPos);
  yPos += 6;

  if (data.generatedByAi) {
    doc.setTextColor(128, 0, 128);
    doc.text("Generated by AI", 14, yPos);
    yPos += 6;
  }

  // Separator line
  yPos += 4;
  doc.setDrawColor(200);
  doc.line(14, yPos, 196, yPos);
  yPos += 10;

  // Content
  doc.setTextColor(0);
  doc.setFontSize(11);

  // Split content into lines that fit the page
  const lines = doc.splitTextToSize(data.content, 182);

  for (const line of lines) {
    if (yPos > 280) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, 14, yPos);
    yPos += 6;
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} | Termly.cc | ${new Date().toLocaleDateString()}`,
      14,
      290
    );
  }

  return doc;
}

/**
 * Export covenant test results to PDF
 */
export function exportCovenantTestToPDF(data: CovenantTestExportData): jsPDF {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(10);
  doc.setTextColor(23, 164, 23); // Termly green
  doc.text("TERMLY - Covenant Test Report", 14, 15);

  // Title
  doc.setFontSize(18);
  doc.setTextColor(0);
  doc.text(`${data.borrowerName} - Covenant Test Results`, 14, 28);

  // Meta info
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Loan: ${data.loanName}`, 14, 38);
  doc.text(`Period End: ${data.periodEndDate}`, 14, 44);
  doc.text(`Tested: ${data.testedAt}`, 14, 50);

  // Summary stats
  const compliant = data.results.filter((r) => r.status === "compliant").length;
  const warning = data.results.filter((r) => r.status === "warning").length;
  const breach = data.results.filter((r) => r.status === "breach").length;

  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(`Summary: ${compliant} Compliant | ${warning} Warning | ${breach} Breach`, 14, 60);

  // Results table
  autoTable(doc, {
    startY: 70,
    head: [["Covenant", "Type", "Value", "Threshold", "Headroom", "Status"]],
    body: data.results.map((r) => [
      r.covenantName,
      r.type.replace("_", " "),
      `${r.calculatedValue.toFixed(2)}x`,
      `${r.operator === "max" ? "≤" : "≥"} ${r.threshold.toFixed(2)}x`,
      `${r.headroomPercentage >= 0 ? "+" : ""}${r.headroomPercentage.toFixed(1)}%`,
      r.status.toUpperCase(),
    ]),
    headStyles: {
      fillColor: [23, 164, 23], // Termly green
      textColor: 255,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 9,
    },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 30 },
      2: { cellWidth: 25, halign: "right" },
      3: { cellWidth: 30, halign: "right" },
      4: { cellWidth: 25, halign: "right" },
      5: { cellWidth: 25, halign: "center" },
    },
    didParseCell: function (data) {
      // Color code status column
      if (data.column.index === 5 && data.section === "body") {
        const status = data.cell.text[0]?.toLowerCase();
        if (status === "compliant") {
          data.cell.styles.textColor = [34, 139, 34];
          data.cell.styles.fontStyle = "bold";
        } else if (status === "warning") {
          data.cell.styles.textColor = [184, 134, 11];
          data.cell.styles.fontStyle = "bold";
        } else if (status === "breach") {
          data.cell.styles.textColor = [220, 20, 60];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} | Termly.cc | Generated ${new Date().toLocaleString()}`,
      14,
      290
    );
  }

  return doc;
}

/**
 * Download a jsPDF document
 */
export function downloadPDF(doc: jsPDF, filename: string): void {
  doc.save(`${filename}.pdf`);
}
